# module info

tts: "tts.google_tts.GoogleTTS"
local_intent: "intent.rasa_intent.RasaIntent"
llm_intent: "intent.llm_intent.ChatGPTIntent"
actions: "actions.all_actions.Actions"

# Optional: Additional settings
settings:
  # MQTT configuration (optional)
  mqtt:
    enabled: true
    broker_host: "192.168.0.1"
    broker_port: 1883
    username: "myuser"
    password: "mypassword"
    keepalive: 60
    qos: 0
  
  # Logging configuration
  logging:
    level: "INFO"
    # format: "%(asctime)s[%(name)s][%(levelname)s] %(message)s"
    format: "[%(asctime)s][%(levelname)s][%(filename)s][%(name)s] - %(message)s"
  
  # Server configuration
  server:
    host: "0.0.0.0"
    port: 8000
    reload: true

